name: data_preparation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2.3
  - pandas=2.2.3
  - dask=2025.2.0
  - dask-jobqueue=0.9.0
  - ipykernel=6.29.5
  - astropy=7.0.1
  - tables-io
  - pip
  - pip:
      - dustmaps==1.0.14